# Generated by Django 5.0.14 on 2026-05-03 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspecciones', '0001_initial'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='movimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movimientos.movimiento'),
        ),
        migrations.AddField(
            model_name='detalleinspeccion',
            name='inspeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecciones.inspeccion'),
        ),
    ]
