# Generated by Django 5.0.14 on 2026-05-04 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_general', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_economico', models.CharField(max_length=50, unique=True, verbose_name='Número de unidad')),
                ('tipo', models.CharField(choices=[('TRACTOR', 'Tractor'), ('REMOLQUE', 'Remolque')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_revision', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.inspeccion')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TALLER_ENTRADA', 'Entrada a taller'), ('TALLER_SALIDA', 'Salida de taller'), ('CORRECCION', 'Corrección')], max_length=30)),
                ('fecha_hora_evento', models.DateTimeField()),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('inconsistente', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('referencia_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.movimiento')),
            ],
        ),
    ]
