# Generated by Django 5.0.14 on 2026-05-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='numero_economico',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de unidad'),
        ),
    ]
