# Generated by Django 5.0.14 on 2026-05-04 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='movimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistica.movimiento'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.sucursal'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='sucursal_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.sucursal'),
        ),
        migrations.AddField(
            model_name='unidadmovimiento',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad_movimientos', to='logistica.movimiento'),
        ),
        migrations.AddField(
            model_name='unidadmovimiento',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidad_movimientos', to='logistica.unidad'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='unidades',
            field=models.ManyToManyField(through='logistica.UnidadMovimiento', to='logistica.unidad'),
        ),
        migrations.AlterUniqueTogether(
            name='unidadmovimiento',
            unique_together={('movimiento', 'unidad')},
        ),
    ]
