# Generated by Django 5.1 on 2026-05-10 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='numero_economico',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número económico'),
        ),
        migrations.AlterField(
            model_name='unidadmovimiento',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='logistica.unidad'),
        ),
        migrations.CreateModel(
            name='Manifiesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('EN_TRANSITO', 'En tránsito'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada_est', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifiestos_destino', to='logistica.sucursal')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifiestos_origen', to='logistica.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadManifiesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifiesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad_manifiestos', to='logistica.manifiesto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifiestos', to='logistica.unidad')),
            ],
            options={
                'unique_together': {('manifiesto', 'unidad')},
            },
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='unidades',
            field=models.ManyToManyField(through='logistica.UnidadManifiesto', to='logistica.unidad'),
        ),
    ]
