# Generated by Django 5.1 on 2026-05-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_manifiesto_unidadmanifiesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TALLER_ENTRADA', 'Entrada a taller'), ('TALLER_SALIDA', 'Salida de taller'), ('CORRECCION', 'Corrección'), ('INSPECCION', 'Inspección')], max_length=30),
        ),
    ]
