# Generated by Django 5.1 on 2026-05-13 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_movimiento_tipo_inspeccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='manifiesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='logistica.manifiesto'),
        ),
    ]
