# Generated by Django 5.1 on 2026-05-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_movimiento_fk_manifiesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifiesto',
            name='folio_hoja_viajera',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Folio hoja viajera'),
        ),
    ]
