# Generated by Django 5.0.14 on 2026-05-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_modelos_detalle_inspeccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallegeneral',
            old_name='año_contenedor',
            new_name='anio_contenedor',
        ),
        migrations.RenameField(
            model_name='detallegeneral',
            old_name='año_remolque',
            new_name='anio_remolque',
        ),
        migrations.AlterField(
            model_name='detallegeneral',
            name='id_caja',
            field=models.CharField(blank=True, max_length=50, verbose_name='# Caja'),
        ),
        migrations.AlterField(
            model_name='detallegeneral',
            name='id_tractor',
            field=models.CharField(blank=True, max_length=50, verbose_name='# Tractor'),
        ),
        migrations.AlterField(
            model_name='detallegeneral',
            name='numero_sello',
            field=models.CharField(blank=True, max_length=50, verbose_name='# Sello'),
        ),
    ]
