# Generated by Django 5.1 on 2026-05-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0010_rename_año_contenedor_detallegeneral_anio_contenedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecaja',
            name='golpes_y_rallones',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Golpes y rayones'),
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='manitas',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='manivelas',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='molduras',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='patines',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='reflejantes',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='remaches_de_carga',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='detallecaja',
            name='soqueteras',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='detallecajavacia',
            name='bisagras',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='detallecajavacia',
            name='libre_olores',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Libre de olores'),
        ),
        migrations.AlterField(
            model_name='detallecajavacia',
            name='limpieza',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='detallecajavacia',
            name='mecanismos_de_cierre',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Mecanismos de cierre'),
        ),
        migrations.AlterField(
            model_name='detallecajavacia',
            name='parches_y_reparaciones',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Parches y reparaciones'),
        ),
        migrations.AlterField(
            model_name='detallecajavacia',
            name='paredes_de_interior',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Paredes de interior'),
        ),
        migrations.AlterField(
            model_name='detallecajavacia',
            name='paredes_integros',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Paredes íntegras'),
        ),
        migrations.AlterField(
            model_name='detallecajavacia',
            name='pisos_integros',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Pisos íntegros'),
        ),
        migrations.AlterField(
            model_name='detallecajavacia',
            name='puertas_simetricas',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Puertas simétricas'),
        ),
        migrations.AlterField(
            model_name='detallecajavacia',
            name='techo_libre_filtraciones',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Techo libre de filtraciones'),
        ),
        migrations.AlterField(
            model_name='detallecajavacia',
            name='techos_integros',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Techos íntegros'),
        ),
    ]
