# Generated by Django 5.0.14 on 2026-05-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0011_caja_choices_sino'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecaja',
            name='bisagras',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
        migrations.AddField(
            model_name='detallecaja',
            name='llantas',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Llantas sin ponchar'),
        ),
        migrations.AddField(
            model_name='detallecaja',
            name='luz_lateral',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Luz lateral (led/normal)'),
        ),
        migrations.AddField(
            model_name='detallecaja',
            name='luz_trasera',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Luz trasera (led/normal)'),
        ),
        migrations.AddField(
            model_name='detallecaja',
            name='receptor_electrico',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, verbose_name='Receptor eléctrico'),
        ),
    ]
