# Generated by Django 5.1 on 2026-05-18 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0012_detallecaja_bisagras_detallecaja_llantas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subinspeccion',
            name='resultado',
        ),
    ]
