# Generated by Django 5.0.14 on 2026-05-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0013_remove_subinspeccion_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='subinspeccion',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
