# Generated by Django 5.0.14 on 2026-06-01 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0014_subinspeccion_completada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallegeneral',
            name='id_caja',
        ),
        migrations.RemoveField(
            model_name='detallegeneral',
            name='id_tractor',
        ),
    ]
