# Generated by Django 5.0.14 on 2026-06-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0015_remove_id_caja_id_tractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='vin',
            field=models.CharField(blank=True, max_length=20, verbose_name='VIN'),
        ),
    ]
