# Generated by Django 5.0.14 on 2026-06-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0016_add_vin_to_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='vin',
            field=models.CharField(max_length=20, unique=True, verbose_name='VIN'),
        ),
    ]
