# Generated by Django 5.0.14 on 2026-06-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0017_vin_unique_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallegeneral',
            name='fianza',
        ),
        migrations.AddField(
            model_name='manifiesto',
            name='numero_fianza',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de fianza'),
        ),
    ]
