# Generated by Django 5.0.14 on 2026-06-01 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0018_move_fianza_to_manifiesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('tipo_linea', models.CharField(choices=[('PROPIA', 'Propia'), ('EXTERNA', 'Externa')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detallegeneral',
            name='linea',
        ),
        migrations.AddField(
            model_name='unidad',
            name='linea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='logistica.linea'),
        ),
    ]
