# Generated by Django 5.0.14 on 2026-06-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0019_add_linea_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallegeneral',
            name='estatus_caja',
            field=models.CharField(blank=True, choices=[('CARGA', 'Carga'), ('VACIA', 'Vacía')], max_length=5, verbose_name='Estatus de caja'),
        ),
    ]
