# Generated by Django 5.0.14 on 2026-06-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0020_add_estatus_caja_to_detallegeneral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallegeneral',
            name='estatus_caja',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='estatus_caja',
            field=models.CharField(blank=True, choices=[('CARGA', 'Carga'), ('VACIA', 'Vacía')], max_length=5, verbose_name='Estatus de caja'),
        ),
    ]
