# Generated by Django 5.1 on 2026-06-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0021_move_estatus_caja_to_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrollanta',
            name='validado',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='estatus_caja',
            field=models.CharField(blank=True, choices=[('CARGA', 'Cargada'), ('VACIA', 'Vacía')], max_length=5, verbose_name='Estatus de caja'),
        ),
    ]
