# Generated by Django 5.0.14 on 2026-05-03 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TALLER_ENTRADA', 'Entrada a taller'), ('TALLER_SALIDA', 'Salida de taller'), ('CORRECCION', 'Corrección')], max_length=30)),
                ('fecha_hora_evento', models.DateTimeField()),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('inconsistente', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('referencia_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movimientos.movimiento')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.sucursal')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidades.unidad')),
            ],
        ),
    ]
