# Generated by Django 5.1 on 2026-05-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('CASETA', 'Caseta'), ('CONTROL', 'Control'), ('PLANEACION', 'Planeación'), ('ADMIN', 'Administrador')], max_length=20),
        ),
    ]
